name: lint
on:
  push:
  pull_request:
  schedule:
    - cron: '14 7 * * *'
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 lint
        uses: py-actions/flake8@v1
